### ISSUE TITLE
Android not working in debug mode

### ISSUE THREAD

**Issue by Jpoliachik** [Telios-org/rn-mobile-client#2]
In debug mode, app will build but crashes immediately at runtime:

```
2021-12-16 05:47:04.248 7218-7218/com.teliosmobile E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.teliosmobile, PID: 7218
    java.lang.RuntimeException: Unable to create application com.teliosmobile.MainApplication: java.lang.RuntimeException: Requested enabled DevSupportManager, but BridgeDevSupportManager class was not found or could not be created
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6695)
        at android.app.ActivityThread.access$1500(ActivityThread.java:249)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2055)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7798)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
     Caused by: java.lang.RuntimeException: Requested enabled DevSupportManager, but BridgeDevSupportManager class was not found or could not be created
        at com.facebook.react.devsupport.a.a(:90)
        at c.a.n.p.<init>(:247)
        at c.a.n.q.b(:287)
        at c.a.n.s.a(:89)
        at c.a.n.s.h(:39)
        at com.teliosmobile.MainApplication.onCreate(:47)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1223)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6690)
        at android.app.ActivityThread.access$1500(ActivityThread.java:249) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2055) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loopOnce(Looper.java:201) 
        at android.os.Looper.loop(Looper.java:288) 
        at android.app.ActivityThread.main(ActivityThread.java:7798) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003) 
     Caused by: java.lang.ClassNotFoundException: com.facebook.react.devsupport.BridgeDevSupportManager
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:454)
        at java.lang.Class.forName(Class.java:379)
        at com.facebook.react.devsupport.a.a(:68)
        at c.a.n.p.<init>(:247) 
        at c.a.n.q.b(:287) 
        at c.a.n.s.a(:89) 
        at c.a.n.s.h(:39) 
        at com.teliosmobile.MainApplication.onCreate(:47) 
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1223) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6690) 
        at android.app.ActivityThread.access$1500(ActivityThread.java:249) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2055) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loopOnce(Looper.java:201) 
        at android.os.Looper.loop(Looper.java:288) 
        at android.app.ActivityThread.main(ActivityThread.java:7798) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003) 
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.facebook.react.devsupport.BridgeDevSupportManager" on path: DexPathList[[zip file "/data/app/~~Mk4V6jt7MkcOCM5DgSS5bw==/com.teliosmobile-heKkpkrFOJmZxG9BrQTWJg==/base.apk"],nativeLibraryDirectories=[/data/app/~~Mk4V6jt7MkcOCM5DgSS5bw==/com.teliosmobile-heKkpkrFOJmZxG9BrQTWJg==/lib/arm64, /data/app/~~Mk4V6jt7MkcOCM5DgSS5bw==/com.teliosmobile-heKkpkrFOJmZxG9BrQTWJg==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:218)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at java.lang.Class.classForName(Native Method) 
        at java.lang.Class.forName(Class.java:454) 
        at java.lang.Class.forName(Class.java:379) 
        at com.facebook.react.devsupport.a.a(:68) 
        at c.a.n.p.<init>(:247) 
        at c.a.n.q.b(:287) 
        at c.a.n.s.a(:89) 
        at c.a.n.s.h(:39) 
        at com.teliosmobile.MainApplication.onCreate(:47) 
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1223) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6690) 
        at android.app.ActivityThread.access$1500(ActivityThread.java:249) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2055) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loopOnce(Looper.java:201) 
        at android.os.Looper.loop(Looper.java:288) 
        at android.app.ActivityThread.main(ActivityThread.java:7798) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003) 

```

**Comment by vitalikgriza** [comment]
@hexadecible I think that's fixed, we can close it
